site_name:        ApacheExpress
site_url:         http://apacheexpress.io/
site_author:      ZeeZide GmbH
copyright:        © ZeeZide GmbH 2018
repo_url:         https://github.com/apacheexpress/
  
docs_dir:    content
site_dir:    docs

theme:       readthedocs
theme_dir:   custom_theme
extra_css:   [ extra.css ]

nav:
  - 'Introduction':         'index.md'
  - 'Installation':         'install.md'
  - 'Routing & Middleware': 'routing.md'
  - 'Templates':            'templates.md'
  - 'SQL Database Access':  'mod_dbd.md'
  - 'HTTP/2':               'http2.md'
  - 'About':                'about.md'
